version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-start-up-ws}-site
    env_file:
      - .env
      - project/.env
    tty: true
    working_dir: /var/www/html
    ports:
      - "${COMPOSE_WEBSERVER_PORT:-80}:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-local-network

networks:
  app-local-network:
    driver: bridge
