version: '3.8'
services:

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-start-up-ws}-frontend
    env_file:
      - .env
    tty: true
    working_dir: /var/www/html
    ports:
      - "${COMPOSE_WEBSERVER_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - app-local-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-start-up-ws}-backend
    env_file:
      - project/.env
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html:cached
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elastic
    networks:
      - app-local-network

  db:
    image: mariadb:10.8
    container_name: ${COMPOSE_PROJECT_NAME:-start-up-ws}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: startup
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-local-network

  redis:
    image: redis:6-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-start-up-ws}-redis
    ports:
      - "6379:6379"
    networks:
      - app-local-network

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: ${COMPOSE_PROJECT_NAME:-start-up-ws}-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-local-network

volumes:
  db_data:
  es_data:

networks:
  app-local-network:
    driver: bridge
