version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-site
    tty: true
    working_dir: /var/www/html
    ports:
      - "${COMPOSE_WEBSERVER_PORT}:3000"
    networks:
      - app-local-network


networks:
  app-local-network:
    driver: bridge
