version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./ops/docker/fpm/Dockerfile
      target: develop
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: develop
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
      - /var/www/html/vendor
    networks:
      - app-local-network
    depends_on:
      - database
      - redis
      - elasticsearch

  nginx:
    build:
      context: .
      dockerfile: ./ops/docker/nginx/Dockerfile
      target: develop
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: develop
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "${COMPOSE_WEBSERVER_PORT}:80"
    networks:
      - app-local-network

  database:
    image: mariadb:10.11
    container_name: ${COMPOSE_PROJECT_NAME}-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-local-network

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-local-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    restart: unless-stopped
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-local-network

networks:
  app-local-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  es_data:
    driver: local
