services:

  app:
    build:
      context: .
      dockerfile: ./ops/docker/fpm/Dockerfile
      target: develop
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: develop
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
    networks:
      - app-local-network

  nginx:
    build:
      context: .
      dockerfile: ./ops/docker/nginx/Dockerfile
      target: develop
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: develop
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "${COMPOSE_WEBSERVER_PORT}:80"
    networks:
      - app-local-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-es
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-docker-cluster
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data-elasticsearch:/usr/share/elasticsearch/data:delegated
    ports:
      - ${COMPOSE_ES_PORT}:9200
    networks:
      - app-local-network

networks:
  app-local-network:
    driver: bridge
volumes:
  data-elasticsearch:
    driver: local
